import { NavTypes, Region } from "./types";
import {
  Home,
  UserRound,
  Computer,
  FileClock,
  Paperclip,
  Handshake,
} from "lucide-react";

export const navMenus: NavTypes[] = [
  {
    id: "jki12",
    title: "Home",
    icon: Home,
    path: "/dashboard",
    emailTest: "",
  },

  {
    id: "maw74",
    title: "Fournitures informatique",
    icon: Computer,
    path: "/dashboard/fournitures-informatiques",
    emailTest: "daffekhadidiatou@gmail.com",
  },
  {
    id: "maw87",
    title: "Fournitures de bureau",
    icon: Paperclip,
    path: "/dashboard/fournitures-de-bureau",
    emailTest: "",
  },
  {
    id: "zop92",
    title: "Utilisateurs",
    icon: UserRound,
    path: "/dashboard/utilisateurs",
    emailTest: "",
  },
  {
    id: "xha51",
    title: "Historique",
    icon: FileClock,
    path: "/dashboard/historique",
    emailTest: "",
  },
  {
    id: "bqp73",
    title: "Entreprise",
    icon: Handshake,
    path: "/dashboard/entreprise",
    emailTest: "",
  },
];

export const regions: Region[] = [
  {
    region: "dakar",
    departments: [
      {
        department: "dakar",
        communes: [
          "Gorée",
          "Dakar-plateau",
          "Fann-Point E-Amitié",
          "Médina",
          "Fass-Gueule-Tapée-Colobane",
          "Grand Dakar",
          "HLM",
          "Biscuiterie",
          "Hann-Bel-Air",
          "Sicap-Liberté",
          "Dieuppeul-Derklé",
          "Yoff",
          "Mermoz-Sacré-Cœur",
          "Ouakam",
          "Grand Yoff",
          "N'gor",
          "Parcelles Assainies",
          "Cambérene",
        ],
      },
      {
        department: "pikine",
        communes: [
          "Pikine Ouest",
          "Pikine Est",
          "Pikine Sud",
          "Guinaw Rails Nord",
          "Guinaw Rails Sud",
          "Thiaroye Gare",
          "Djidah Thiaroye Kao",
          "Diack Sao",
          "Thiaroye sur Mer",
          "Diamaguène-Sicap Mbao",
          "Keur Massar",
          "Daliford",
          "Malika",
          "M'bao",
          "Yeumbeul Sud",
          "Yeumbeul Nord",
        ],
      },
      {
        department: "guédiawaye",
        communes: [
          "Wakhinane Nimzatt",
          "Sam Notaire",
          "Médina Gounass",
          "Ndiarème Limamoulaye",
          "Golf Sud",
        ],
      },
      {
        department: "rufisque",
        communes: [
          "Rufisque",
          "Bargny",
          "Sébikotane",
          "Diamniadio",
          "Jaxaay-Parcelles Niakoul Rap",
          "Bambilor",
          "Sangalkam",
          "Sendou",
          "Yene",
          "Tivaouane Peulh-Niagha",
          "Rufisque Centre (nord)",
          "Rufisque Est",
          "Rufisque Ouest",
        ],
      },
    ],
  },
  {
    region: "diourbel",
    departments: [
      {
        department: "diourbel",
        communes: [
          "Diourbel",
          "Dankh Sene",
          "Gade Escale",
          "N'dindy",
          "Keur N'galgou",
          "Taiba Moustapha",
          "Touba Lappe",
          "N'doulo",
          "N'gohe",
          "Patar",
          "Tocky Gare",
          "Touré M'bondé",
        ],
      },
      {
        department: "bambey",
        communes: ["Bambey", "Baba Garage", "Lambaye", "N'goye"],
      },
      {
        department: "mbacké",
        communes: [
          "Mbacké",
          "Dendeye Gouye Gui",
          "Darou Salam Typ",
          "N’dioumane  T.Thiekene",
          "Kael",
          "Touba M'boul",
          "Madina",
          "Darou Nahim",
          "Taiba Tieckene",
          "Dalla N'Gabou",
          "Missirah",
          "N'Ghaye",
          "Touba Fall",
          "Touba Mosquée",
          "Sadio",
          "Taïf",
        ],
      },
    ],
  },
  {
    region: "fatick",
    departments: [
      {
        department: "fatick",
        communes: [
          "Fatick",
          "Diofior",
          "Diaoule",
          "Mbelacadiao",
          "Ndiob",
          "Thiar Ndialgui",
          "Fimela",
          "Loul-Sessene",
          "Palmarin Facao",
          "Djilasse",
          "Ngayokheme",
          "Niakhar",
          "Patar",
          "Diarere",
          "Diouroup",
          "Tattaguine",
        ],
      },
      {
        department: "foundiougne",
        communes: [
          "Foundiougne",
          "Sokone",
          "Passy",
          "Karang Poste",
          "Soum",
          "Djilor",
          "Diossong",
          "Diagne Barka",
          "Mbam",
          "Niassene",
          "Bassoul",
          "Dionewar",
          "Djirnda",
          "Keur S.Diane",
          "Keur Samba Gueye",
          "Nioro Alassane Tall",
          "Toubacouta",
        ],
      },
      {
        department: "gossas",
        communes: [
          "Gossas",
          "Mbar",
          "Colobane",
          "Ndiene Lagane",
          "Ouadiour",
          "Patar Lia",
        ],
      },
    ],
  },
  {
    region: "kaffrine",
    departments: [
      {
        department: "kaffrine",
        communes: [
          "Kaffrine",
          "N'ganda",
          "Boulel",
          "Gniby",
          "Kahi",
          "Diokoul M’belbouck",
          "Kathiote",
          "Medinatoul Salam 2",
          "Diamagadio",
        ],
      },
      {
        department: "birkilane",
        communes: [
          "Birkilane",
          "Keur Mboucki",
          "Touba M'bella",
          "Diamal",
          "Mabo",
          "N'Diognick",
          "Mbeuleup",
          "Ségré Gatta",
        ],
      },
      {
        department: "koungheul",
        communes: [
          "Koungheul",
          "Saly Escal",
          "Fass Thiekene",
          "Ida Mouride",
          "Lour Escale",
          "Ribot Escale",
          "Gainthe Pathé",
          "Maka Yop",
          "Missirah Wadene",
        ],
      },
      {
        department: "malem hodar",
        communes: [
          "Malem Hodar",
          "Darou Miname II",
          "N'dioum N'gainth",
          "Khelcom",
          "Ndiobene Samba Lamo",
          "Dianké Souf",
          "Sagna",
        ],
      },
    ],
  },
  {
    region: "kaolack",
    departments: [
      {
        department: "kaolack",
        communes: [
          "Kaolack",
          "Kahone  ",
          "Gandiaye  ",
          "Ndoffane  ",
          "Sibassor  ",
          "Keur soce  ",
          "Ndiaffate  ",
          "Ndiedieng  ",
          "Latmingue  ",
          "Thiare  ",
          "Keur baka  ",
          "Dya  ",
          "Ndiebel  ",
          "Thiomby",
        ],
      },
      {
        department: "guinguinéo",
        communes: [
          "Guinguineo",
          "Fass",
          "Mboss",
          "Mbadakhoune",
          "Ndiago",
          "Ndiago",
          "Ngathie naoude",
          "Khelcom birame",
          "Gagnick",
          "Nguelou",
          "Ourour",
          "Dara mboss",
          "Panal ouolof",
        ],
      },
      {
        department: "nioro du rip",
        communes: [
          "Nioro",
          "Keur madiabel",
          "Kayemor",
          "Medina-sabakh",
          "Ngayene",
          "Gainte kaye",
          "Porokhane",
          "Taïba niassene",
          "Dabaly",
          "Darou salam",
          "Keur maba diakhou",
          "Ndrame escale",
          "Wack ngouna",
          "K. mandongo",
        ],
      },
    ],
  },
  {
    region: "kédougou",
    departments: [
      {
        department: "kédougou",
        communes: [
          "Kédougou",
          "Bandafassi",
          "Tomboronkoto",
          "Dindifelo",
          "Ninefecha",
          "Dimboli",
          "Fongolembi",
          "Fongolembi",
        ],
      },
      {
        department: "salémata",
        communes: [
          "Salémata",
          "Dakateli",
          "Kevoye",
          "Dar Salam",
          "Ethiolo",
          "Oubadji",
        ],
      },
      {
        department: "saraya",
        communes: [
          "Saraya",
          "Médina Baffé",
          "Bembou",
          "Khossanto",
          "Missirah Sirimana",
          "Sabodola",
        ],
      },
    ],
  },
  {
    region: "kolda",
    departments: [
      {
        department: "kolda",
        communes: [
          "Kolda",
          "Dabo",
          "Salikégné",
          "Saré Yoba Diega",
          "Dioulacolon",
          "Médina El Hadji",
          "Tankantto Escale",
          "Guiro Yero Bocar",
          "Bagadadji",
          "Coumbacara",
          "Mampatim",
          "Dialambere",
          "Médina Cherif",
          "Saré Bidji",
          "Thietty",
        ],
      },
      {
        department: "médina yoro foulah",
        communes: [
          "Médina Yoro Foulah",
          "Pata",
          "Fafacourou",
          "Badion",
          "Ndorna",
          "Bignarabe",
          "Bourouco",
          "Koulinto",
          "Dinguiraye",
          "Kerewane",
          "Niaming",
          "Niaming",
        ],
      },
      {
        department: "vélingara",
        communes: [
          "Vélingara",
          "Diaoube-Kabendou",
          "Kounkané",
          "Bonconto",
          "Linkering",
          "Médina Gounass",
          "Sinthing Koundara",
          "Ouassadou",
          "Paroumba",
          "Pakour",
          "Kandia",
          "Saré Coly Sallé",
          "Nemataba",
          "Kandiaye",
        ],
      },
    ],
  },
  {
    region: "louga",
    departments: [
      {
        department: "louga",
        communes: [
          "Ndiagne",
          "Coki",
          "Pete ouarack",
          "Thiamene cayor",
          "Guet ardo",
          "Gande",
          "K.momar sarr",
          "Nguer mala",
          "Syer",
          "Kelle gueye",
          "Mbediene",
          "Niomre",
          "Leona",
          "Ngueune sarr",
          "Sakal",
        ],
      },
      {
        department: "kébémer",
        communes: [
          "Gueoul",
          "Darou marnane",
          "Darou mousty",
          "Mbadiane",
          "Ndoyene",
          "Sam yabal",
          "Touba merina",
          "Mbacke cadior",
          "Badegne ouolof",
          "Diokoul diawrigne",
          "Kab gaye",
          "Ndande",
          "Thieppe",
          "Kanene ndiob",
          "Loro",
          "Sagatta gueth",
          "Thiolom fall",
          "Ngourane ouolof",
        ],
      },
      {
        department: "linguère",
        communes: [
          "Linguere",
          "Dahra",
          "Mbeuleukhe",
          "Barkedji",
          "Gassane",
          "Thiargny",
          "Thiel",
          "Dodji",
          "Labgar",
          "Ouarkhoh",
          "Kamb",
          "Mboula",
          "Tessekre forage",
          "Yang yang",
          "Boulal",
          "Deali",
          "Sagatta djolof",
          "Thiamene djolof",
          "Affe djoloff",
        ],
      },
    ],
  },
  {
    region: "matam",
    departments: [
      {
        department: "matam",
        communes: [
          "Matam",
          "Ourossogui",
          "Thilogne",
          "Nguidilogne",
          "Agnam-civol",
          "Orefonde",
          "Dabia",
          "Bokidiawe",
          "Nabadji-civol",
          "Ogo",
        ],
      },
      {
        department: "kanel",
        communes: [
          "Kanel",
          "Semmé",
          "Dembancane",
          "Hamady Ounaré",
          "Sinthiou bamanbe-banadji",
          "Odobéré",
          "Bokiladji",
          "Orkadieré",
          "Aouré",
          "Ndendory",
          "Ouro Sidy",
          "Ouro Sidy",
        ],
      },
      {
        department: "ranérou-ferlo",
        communes: [
          "Ranérou",
          "Lougré Thioly",
          "Velingara",
          "Oudalaye",
          "Oudalaye",
        ],
      },
    ],
  },
  {
    region: "saint-louis",
    departments: [
      {
        department: "saint-louis",
        communes: [
          "Saint-Louis",
          "Gandon",
          "Mpal",
          "Fass Ngom",
          "N'diebene Gandiole",
        ],
      },
      {
        department: "dagana",
        communes: [
          "Dagana",
          "Richard-Toll",
          "Ross-Béthio",
          "Gae",
          "Ndombo Sandjiry",
          "Mbane",
          "Bokhol",
          "Diama",
          "Ngnith",
          "Ronkh",
        ],
      },
      {
        department: "podor",
        communes: [
          "Podor",
          "Aéré Lao",
          "Ndioum",
          "Ndiandane",
          "Bodé Lao",
          "Démette",
          "Galoya Toucouleur",
          "Guédé Chantier",
          "Mboumba",
          "Aéré Lao",
          "Pété",
          "Walaldé",
          "Médina Ndiathbé",
          "Dounga Lao",
          "Mery",
          "Boké Dialloubé",
          "Mbolo Birane",
          "Fanaye",
          "Ndiayene Pendao",
          "Dodel",
          "Gamadji Saré",
          "Guédé Village",
        ],
      },
    ],
  },
  {
    region: "sédhiou",
    departments: [
      {
        department: "sédhiou",
        communes: [
          "Sedhiou",
          "Marsassoum",
          "Dianah malary",
          "Diende",
          "Sakar",
          "Diannah ba",
          "Koussy",
          "Oudoucar",
          "Sama kanta peulh",
          "Benet- bijini",
          "Sansamba",
          "Djibabouya",
          "Bambali",
          "Djiredji",
        ],
      },
      {
        department: "bounkiling",
        communes: [
          "Bounkiling",
          "Madina wandifa",
          "Ndiamacouta",
          "Boghal",
          "Tankon",
          "Djinany",
          "Ndiamalathiel",
          "Bona",
          "Diacounda",
          "Inor",
          "Kandion mangana",
          "Diaroume",
          "Diambaty",
          "Faoune",
        ],
      },
      {
        department: "goudomp",
        communes: [
          "Goudomp",
          "Diattacounda",
          "Samine",
          "Tanaff",
          "Djibanar",
          "Kaour",
          "Mangaroungou santo",
          "Simbadi Balanté",
          "Yarang Balanté",
          "Karantaba",
          "Kolibantang",
          "Niagha",
          "Simbandi Brassou",
          "Baghere",
          "Diouboudou",
        ],
      },
    ],
  },
  {
    region: "tambacounda",
    departments: [
      {
        department: "tambacounda",
        communes: [
          "Tambacounda",
          "Koussanar",
          "Sinthiou Malem",
          "Makacoulibatang",
          "N'doga Babacar",
          "Niani Toucouleur",
          "Dialacoto",
          "Missirah",
          "Nette Boulou",
        ],
      },
      {
        department: "bakel",
        communes: [
          "Bakel",
          "Diawara",
          "Kidira",
          "Gathiary",
          "Madina foulbe",
          "Sadatou",
          "Toumboura",
          "Bele",
          "Sinthiou-fissa",
          "Ballou",
          "Gabou",
          "Moudery",
        ],
      },
      {
        department: "goudiry",
        communes: [
          "Goudiry",
          "Bala",
          "Goumbayel",
          "Koar",
          "Dougue",
          "Boynguel Bamba",
          "Koussan",
          "Sinthiou Mamadou Boubou",
          "Bani Israel",
          "Boutoucoufara",
          "Dianke Makha",
          "Komoti",
          "Koulor",
          "Sinthiou Bocar Ali",
        ],
      },
      {
        department: "koumpentoum",
        communes: [
          "Koumpentoum",
          "Malem niani",
          "Bamba thialene",
          "Kahene",
          "Mereto",
          "N’dame",
          "Kouthia gaydi",
          "Kouthiaba wolof",
          "Pass koto",
          "Payar",
        ],
      },
    ],
  },
  {
    region: "thiès",
    departments: [
      {
        department: "thiès",
        communes: [
          "Khombole",
          "pout",
          "Notto",
          "Tassette",
          "N’dieyene sirakh",
          "N’goundiane",
          "Thienaba",
          "Touba toul",
          "Diender guedji",
          "Fandene",
          "Keur moussa",
          "Thies nord",
          "Thies est",
          "Thies ouest",
        ],
      },
      {
        department: "mbour",
        communes: [
          "Joal- fadiouth",
          "M’bour",
          "Guekokh",
          "N’gaparou",
          "Popoguine",
          "Saly portudal",
          "Somone",
          "Fissel",
          "N’diaganiao",
          "N’gueniene",
          "Sandiara",
          "Sessene",
          "Malicounda",
          "Diass",
          "Sindia",
        ],
      },
      {
        department: "tivaouane",
        communes: [
          "Tivaouane",
          "Mékhé",
          "Kayar",
          "Mboro",
          "Meouane",
          "Taiba Ndiaye",
          "Darou Khoudoss",
          "Koul",
          "Merina Dakhar",
          "Pekesse",
          "Mbayene",
          "N'gandiouf",
          "Niakhene",
          "Thilmakha",
          "Cherif Lô",
          "Mont-Rolland",
          "Notto Gouye Diama",
          "Pire Goureye",
          "Pambal",
        ],
      },
    ],
  },
  {
    region: "ziguinchor",
    departments: [
      {
        department: "ziguinchor",
        communes: [
          "Ziguinchor",
          "Adeane",
          "Boutoupa camara",
          "Niaguis",
          "Enampore",
          "Nyassia",
        ],
      },
      {
        department: "bignona",
        communes: [
          "Bignona",
          "Thionck-essyl",
          "Diouloulou",
          "Djibidione",
          "Oulampane",
          "Sindian",
          "Suelle",
          "Balingore",
          "Diegoune",
          "Karthiack",
          "Mangagoulack",
          "Mlomp",
          "Coubalan",
          "Niamone",
          "Ouonck",
          "Tenghory",
          "Djinaki",
          "Kafountine",
          "Kataba i",
        ],
      },
      {
        department: "oussouye",
        communes: [
          "Oussouye",
          "Djembering",
          "Santhiaba manjacque",
          "Mlomp",
          "Oukout",
        ],
      },
    ],
  },
];

export const ages: string[] = [
  "18",
  "19",
  "20",
  "21",
  "22",
  "23",
  "24",
  "25",
  "26",
  "27",
  "28",
  "29",
  "30",
  "31",
  "32",
  "33",
  "34",
  "35",
  "36",
  "37",
  "38",
  "39",
  "40",
  "41",
  "42",
  "43",
  "44",
  "45",
  "46",
  "47",
  "48",
  "49",
  "50",
  "51",
  "52",
  "53",
  "54",
  "55",
  "56",
  "57",
  "58",
  "59",
  "60",
];
